### ISSUE TITLE
[Feature Request] Local cache : Don't use .tmp extensions

### ISSUE THREAD

**Issue by Nonobis** [Suwayomi/Suwayomi-Server#100]
**PLEASE READ THIS**

---

I love this app, perfect for using tachiyomi on self hosted server :) But ....

## What feature should be added to Tachidesk?
In local cache folder, save image with right extension (png/jpg ...), not .tmp.

##  Why/Project's Benefit/Existing Problem
More productivity when creating cbz manually... for archiving comics/manga purpise (sorry self hosted nerd here)

**Comment by Nonobis** [comment]
@AriaMoradi  : Thanks for fix :) , but do you think you caoul change extension of existing file ? Or we need to delete local cache ?

**Comment by AriaMoradi** [comment]
delete local cache

**Comment by Nonobis** [comment]
thks 👍
