### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by RayZ3R0** [Suwayomi/Suwayomi-Server#111]
It is written that downloading is partially available but i couldn't find any download option ;-;

**Comment by voltrare** [comment]
It caches the image as you read
Check
https://github.com/Suwayomi/Tachidesk/wiki/Troubleshooting

**Comment by RayZ3R0** [comment]
Ah, okay. But isn't there any way of downloading all the chapters like tachiyomi yet?

**Comment by AriaMoradi** [comment]
I'll implement it in one of the upcoming updates.
