### ISSUE TITLE
Tachidesk doenst start

### ISSUE THREAD

**Issue by ghost** [Suwayomi/Suwayomi-Server#119]
![unknown](https://user-images.githubusercontent.com/66573644/120119338-ea4fef00-c19f-11eb-896c-b92f166d2dd3.png)
Same problem was normaly solved by deleting local app data but after deleting it 2 times i can assure you it is not the problem i had restarted my pc closed running java in task manager still it loads for a secong then stops

**Comment by AriaMoradi** [comment]
Delete all data and run Tachidesk again then give me the output of cmd.

Then upload your database file here please.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/66573644/120120293-ef636d00-c1a4-11eb-9f50-c3606b12c242.png)
about db files i cant upload them here gb gives unsupported extension error i can send them via discord or gmail if you want other than this is cmd after reinstalling app from github and deleting local appdata and restarting

**Comment by AriaMoradi** [comment]
Delete the directory called "Tachidesk", don't double click on Tachidesk.jar or any of the launchers, just directly run it from cmd again and give me the result. Your screenshot indicates that the app was run before or you didn't delete the right directory. make sure you are deleting `C:\Users\Ugandan Presidant\AppData\Local\Tachidesk`

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/66573644/120121841-62251600-c1ae-11eb-8253-4d9bb682f43d.png)
jar file does nothing electron is not found

**Comment by ghost** [comment]
btw i had tried on another computer its not working bat files shows a cmd window and closes in a second

**Comment by voltrare** [comment]
yo try this
START "Tachidesk Electron Launcher.bat"

(you need those "" )

try to redownload

**Comment by ghost** [comment]
i redownloaded file like 7 times if i try to open it from cmd windows cant find the file and if i open it from folder it opens up cmd for sec and disappears

**Comment by ghost** [comment]
but i did delete appdata

**Comment by AriaMoradi** [comment]
I've thought long and hard about it, And the only way I can think of is Migration number 1 being successful but disk is too slow to accept writes? or a buffer is dirty? and the second fails as the first one's not written yet?

But the issue seems to be consistent?

**Comment by ghost** [comment]
funny thing is it gave me the same error on a fresh new comp too maybe its about windows itself its so weird even debug launcher isnt working everything opens up for a second and closes but appdata creates a folder jar file does nothing sometimes i can see something on task manager but no results electron is showing this and crashes a sec after in discord they did mention about trying to implement an older verison etc but after deleting appdata 20 times i no longer comprehend what this mess is 
![image](https://user-images.githubusercontent.com/66573644/120901318-be6eb680-c642-11eb-9eeb-d082a8cf7f45.png)

**Comment by AriaMoradi** [comment]
@HeWhoBreedsPestilence 
- What's your windows language set to?
- If it's not English then set it to English, delete the data and try again.

**Comment by AriaMoradi** [comment]
Quote from discord:
> I have tracked the issue and it's due to system localization settings, the Turkish locale is weird, it converts every I to it's turkish counterpart, so setting your locale(language?) to turkish cased this error, returning to English should fix it in theory

reference: https://garygregory.wordpress.com/2015/11/03/java-lowercase-conversion-turkey/

**Comment by AriaMoradi** [comment]
Closing as there hasn't been any response from the OP.
