### ISSUE TITLE
[Bug] Tachidesk doesn't restore manga in categories

### ISSUE THREAD

**Issue by ahmubashshir** [Suwayomi/Suwayomi-Server#125]
## Device information
- Tachidesk version: v0.4.2-r645
- Server Operating System: EndeavourOS
- Server Desktop Environment: Xfce 4.16
- Server JVM version: OpenJDK 15.0.2.u7
- Client Operating System: EndeavourOS
- Client Web Browser: Firefox 88.0.1

## Steps to reproduce
1. Go to Settings > Backup > Restore Legacy Backup
2. Select a backup with multiple categories.

### Expected behavior
Restored manga should be in their backed up categories.

### Actual behavior
All manga are listed under the default category.

**Comment by ghost** [comment]
No need u can just restore the Tachidesk Folder in `%localappdata%/Tachidesk` copy it and save it to ur one drive or anywhere u want and then when u will install tachidesk just go to `%appdata%` and paste the Tachidesk folder u just copied and replace the file in Destination. :) Simple .

**Comment by ahmubashshir** [comment]
> No need u can just restore the Tachidesk Folder in `%localappdata%/Tachidesk` copy it and save it to ur one drive or anywhere u want and then when u will install tachidesk just go to `%appdata%` and paste the Tachidesk folder u just copied and replace the file in Destination. :) Simple .

I tried to restore backups from tachiyomi, it restores all manga in default category.

**Comment by ghost** [comment]
No need bro u can restore ur localappdata folder 
Follow this steps- 
1) Press `Windows key + R` 
2) Then type `%localappdata%` in the run box and then press enter
3) Find the `Tachidesk` folder and copy it and save it in a safe place. 
4) Now when u install a new tachidesk press `Windows key + R`  again 
5) Type `%localappdata%` in run box and press enter
6) And then move ur `Tachidesk` folder  (that u have saved) in that location and click on replace this file in the location. 
7) Done :)

**Comment by ahmubashshir** [comment]
Can't you understand???
	Mubashshir

**Comment by ahmubashshir** [comment]
I'm switching over from tachiyomi android... I created legacy backup 
there... now I'm trying to restore the backup from my phone to my 
desktop. Tachidesk restores the manga, but it doesn't restore them in 
their respective category. I have over 200 manga in my library... so 
reorganizing them manually is a pain.
	Mubashshir

**Comment by ahmubashshir** [comment]
And I'm a linux user. so, it's $XDG_DATA_HOME/Tachidesk, not 
%localappdata%/Tachidesk
	Mubashshir

**Comment by ahmubashshir** [comment]
If you don't know how to fix this, then don't reply.
	Mubashshir

**Comment by ghost** [comment]
Then u should say that. That u use linux. When in the issue it said which OS u said `endeavour OS` what does that mean ? U should say linux. I thought u are using windows or mac because everyone uses that.

**Comment by ahmubashshir** [comment]
What my OS has to do with this particular issue? As far as I know, this projects goal is to be compatible with [tachiyomi]. So, if I can't restore my library from [tachiyomi] without breaking structure, then it is a bug and should be fixed. I think I can reproduce this issue in other platforms.
Try restoring [this backup](https://github.com/Suwayomi/Tachidesk/files/6816315/tachiyomi_2021-07-14_19-11.json.gz), it should have been restored like this
![Screenshot_2021-07-14_19-25-44](https://user-images.githubusercontent.com/24864366/125629774-40eb3ce9-59c5-4610-a7ed-f0a52fe2611c.png)|![Screenshot_2021-07-14_19-26-26](https://user-images.githubusercontent.com/24864366/125629841-722a88d1-1edf-47f9-b933-a03743095a9b.png)|![Screenshot_2021-07-14_19-26-42](https://user-images.githubusercontent.com/24864366/125629877-0842fb36-9cb5-49ca-8bc1-0cb9eafb29b8.png)
:---:|:---:|:---:

but it restores all manga in default category like this,
![Screenshot_2021-07-14_19-29-04](https://user-images.githubusercontent.com/24864366/125630259-df704c76-ae57-4410-912c-a654c57a1e03.png)|![Screenshot_2021-07-14_19-29-24](https://user-images.githubusercontent.com/24864366/125630326-782207b6-3572-41b0-8411-b823344a7a2b.png)|![Screenshot_2021-07-14_19-29-46](https://user-images.githubusercontent.com/24864366/125630457-e7a73a13-a656-4799-8038-407c37d62a80.png)
:---:|:---:|:---:


[tachiyomi]: https://tachiyomi.org

**Comment by AriaMoradi** [comment]
Legacy backups are dead, no point in fixing this issue.
