### ISSUE TITLE
[Bug] Displays "downloaded" in the chapter selection menu after deletion

### ISSUE THREAD

**Issue by BaccanoMob** [Suwayomi/Suwayomi-Server#126]
I thought this would be worth mentioning. Since there is no delete option available yet (and me running out spaces quickly in C). I deleted the folder manually in the Local folder. 

Expected Behavior: 
It should have reset to the way it was before,
    ->removed the "downloaded" under the chapter. 
    ->Option to download again or just view normally.

Actual Behavior: 
The "downloaded" is stuck with the chapter. The chapter would not load up anymore.

If it does load up, the image file goes to the download folder (though only 1 image made its way in my case, I think it is because to create the folder again but later got stuck with infinite loading sign because the folder does not contain any other image files than the last page viewed)

This does not seem to be the case if a chapter which is not downloaded. It is viewed normally after being deleted and a new folder pops up just fine.

**Comment by AriaMoradi** [comment]
this was fixed in v0.5.0
