### ISSUE TITLE
[Bug] Mangadex extension installation fails to be recognized 

### ISSUE THREAD

**Issue by BaccanoMob** [Suwayomi/Suwayomi-Server#139]
Clicking install or update Mangadex (maybe other sources) does not properly install the extension. The local folder has the apk and jar file but the manga sources page does not show mangadex.

![image](https://user-images.githubusercontent.com/82655889/121673675-6c4deb00-cab1-11eb-98a6-ab7114681f3a.png)

![image](https://user-images.githubusercontent.com/82655889/121673725-7f60bb00-cab1-11eb-8cbb-1359a7825bdb.png)

First tried updating the extension and then installing after deleted local folder.

### Expected behavior
Should display the extension in the Manga Source tab to browse/search.

### Actual behavior
Installs/updates (or i think so) but fails to recognize.

**Comment by AriaMoradi** [comment]
Does this issue still persist?

**Comment by Syer10** [comment]
Im pretty sure this happens if you have an extension installed in the file system but its not in the db, so it cant install it properly

**Comment by AriaMoradi** [comment]
> Im pretty sure this happens if you have an extension installed in the file system but its not in the db, so it cant install it properly

Should be fixable with a data delete?

**Comment by Syer10** [comment]
It is ya

**Comment by AriaMoradi** [comment]
closing

**Comment by MenacingPerson** [comment]
I am on Linux with this exact issue, but deleting everything in ~/.local/share/Tachidesk does not bring the extension back.

**Comment by MenacingPerson** [comment]
Oh, it was just because I ticked do not show nsfw
