### ISSUE TITLE
[Bug] Source(s) don't disapper even if you uninstall its extension

### ISSUE THREAD

**Issue by joseph619** [Suwayomi/Suwayomi-Server#14]
What the title says. I installed Batoto then uninstalled, none of its sources disappeared from sources screen.

**Comment by AriaMoradi** [comment]
I tried to reproduce your issue but sources disappeared as they should, could you describe exactly how to reproduce this bug?

**Comment by joseph619** [comment]
Apprently the issue is that the extension itself doesn't uninstall when you click uninstall, that's why source doesn't vanish

**Comment by AriaMoradi** [comment]
One possible reproduction method: (but doesn't seem related to OP's issue)
1- install an extension and put a manga from one the extensions into library
2- install fails: Manga to Source referral integrity Error
