### ISSUE TITLE
[Feature Request] Add downloads page progress to the api

### ISSUE THREAD

**Issue by Syer10** [Suwayomi/Suwayomi-Server#140]
## What feature should be added to Tachidesk?
Add page progress to the DownloadChapter object, so clients can display 5 out of 50 reliably.

##  Why/Project's Benefit/Existing Problem
This is already available internally, and just needs to be added to the download object, doing (progress * pageCount) is unreliable as it deals with floating point numbers.

**Comment by AriaMoradi** [comment]
will replace progress with an Int that represents the downloaded page count

**Comment by AriaMoradi** [comment]
Is this resolved? @Syer10

**Comment by Syer10** [comment]
It is ya
