### ISSUE TITLE
[Feature Request] Option for deleting downloads

### ISSUE THREAD

**Issue by arbuilder** [Suwayomi/Suwayomi-Server#141]
## Device information
- Tachidesk version: v0.4.2 latest stable
- Server Operating System: win 10
- Server Desktop Environment: Docker
- Client Web Browser: Google Chrome latest

### Feature request
Currently we don't have option for deleting _manual download_ / _download while reading_  chapters. Also if we manually delete the chapters it should reflect that.

**Comment by AriaMoradi** [comment]
Also the app should automatically mark as not downloaded when chapter dir/images are deleted by the user.

**Comment by arbuilder** [comment]
_download while reading_ could be deleted by a simple option in settings `delete cached  chapters` (showing the current size)
for deleting manual download we could show downloaded manga in `Download ` section (like `Library`) where it would be easier to delete all the downloaded manga

> Also if we manually delete the chapters it should reflect that.

both cases will be covered by this.
- app should automatically mark as not downloaded when chapter dir/images are deleted by the user.
- deleting the cache (download while reading) manually should also reflect in the Tachidesk as `delete cached chapters` 0 byte

**Comment by AriaMoradi** [comment]
fixed in 6bc19af041a8c12ce928f0eb562ee011d3bb4a77

**Comment by arbuilder** [comment]
Covered in new preview release
