### ISSUE TITLE
Anime Extension page not working

### ISSUE THREAD

**Issue by nishantchauhan949** [Suwayomi/Suwayomi-Server#145]
![image](https://user-images.githubusercontent.com/29421897/122656294-c405e980-d176-11eb-9db7-5189c25e925d.png)

### Expected behavior
Show the anime extensions available to install.

### Actual behavior
Just showing `loading...`

**Comment by ghost** [comment]
Watch anime in - https://gogoanime.pe

**Comment by Syer10** [comment]
> Watch anime in - https://gogoanime.pe

Please do not advertise here

**Comment by ghost** [comment]
sorry nvm

**Comment by danilanosikov** [comment]
still, issue is present.

**Comment by AriaMoradi** [comment]
Updates around anime extensions will be tracked in #164, closing.
