### ISSUE TITLE
Error when cloning repository

### ISSUE THREAD

**Issue by mostidaniel** [Suwayomi/Suwayomi-Server#15]
I received this error when trying to clone the repo branch of this repository:

`This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

I also cannot download the precompiled releases through GitHub. It just downloads a corrupted file.
Are there any other ways for me to mitigate this problem?

**Comment by AriaMoradi** [comment]
there no longer is any repo branch, binary releases will be uploaded manually, by me.
