### ISSUE TITLE
[Bug] Nhentai extension not working 

### ISSUE THREAD

**Issue by ghost** [Suwayomi/Suwayomi-Server#151]
## Device information
- Tachidesk version: (Example: v0.2.3-r255-win32)- v.0.4.3-r670 stable Win x64
- Server Operating System: (Example: Ubuntu 20.04)-  Ubuntu 20.04
- Server Desktop Environment: N/A or (Example: Gnome 40)  - docker
- Server JVM version: bundled with win32 or (Example: Java 8 Update 281 or OpenJDK 8u281)  - Don't Know 
- Client Operating System: <usually the same as above Server Operating System> - Win 10 x64
- Client Web Browser: (Example: Google Chrome 89.0.4389.82) - Mozilla Firefox  89.0.2 Stable 

## Steps to reproduce
1. Go to manga extensions and download nhentai extension 
2. Then search any doujin and try to click it and open it.
3. Pages are not loading

### Expected behavior
I expected that the pages should load and I would be able to read the Doujin. 

### Actual behavior
The pages kept on buffering 
![image](https://user-images.githubusercontent.com/69617708/124653503-ffb0eb00-deba-11eb-9e50-79c6fdfaa521.png)

**Comment by Syer10** [comment]
Known issue https://github.com/Suwayomi/Tachidesk/issues/17
