### ISSUE TITLE
[Feature Request] Automatic downloads

### ISSUE THREAD

**Issue by hazre** [Suwayomi/Suwayomi-Server#157]
## What feature should be added to Tachidesk?
An automatic download function that works similar to how something like Sonarr works. Basically it would let you "Monitor" ongoing Manga/LN/etc for new chapters/volumes.

User should be able to set a exact schedule for how often the monitoring should run, for example every hour.

##  Why/Project's Benefit/Existing Problem
This would get rid of manual interactions, each time a new chapter releases. It would make the whole experience pretty much set it and forget it, which would be pretty nice.

**Comment by wisewtf** [comment]
Any updates on this? I am sad to see this isn't supported already. :(

**Comment by himsin** [comment]
+1

**Comment by Syer10** [comment]
Addressed by #593
