### ISSUE TITLE
extension and sours

### ISSUE THREAD

**Issue by nezor-dev** [Suwayomi/Suwayomi-Server#16]

**Comment by nezor-dev** [comment]
those are the only 2 taps that are showing for me and they show the text wait nothing more

**Comment by nezor-dev** [comment]
this happens when i have the app running on a server
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:4567/api/v1/source/list. (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.`

**Comment by AriaMoradi** [comment]
I don't understand what you are talking about in the second comment.
And your third comment should not happen, CORS is set to * so wherever the request comes from it should work fine, I need more info on how to reproduce it, also the version of the app you are running.

**Comment by AriaMoradi** [comment]
This bug will be fixed in the next release

**Comment by AriaMoradi** [comment]
@NezorPlay Test v0.2.1 out and tell me if the issue persists.
