### ISSUE TITLE
I compressed the icon.

### ISSUE THREAD

**Issue by K0-RR** [Suwayomi/Suwayomi-Server#169]
Normally I open prs with optimized assets (lossless compression by `oxipng`) but this time I noticed the https://github.com/Suwayomi/Tachidesk/blob/master/webUI/src/public/favicon.png and https://github.com/Suwayomi/Tachidesk/blob/master/server/src/main/resources/icon/faviconlogo.png are huge (in dimensions and weight). Does this icon need to be this big? I don't think it is displayed anywhere in its full resolution.

I also tried some lossy compression - reduced the color palette to 10 since the icon is simple enough. It went from 579 KB to 48,0 KB. Then resized it to 2000x and got this 18.7 KB file:
![favicon (1)](https://user-images.githubusercontent.com/43277609/128156939-39bb27e8-91da-4b07-8d94-9defacff6ba4.png)

**Comment by AriaMoradi** [comment]
Technically making it x512 is fine too

**Comment by AriaMoradi** [comment]
closing after #171
