### ISSUE TITLE
[Meta] Extensions known that don't work

### ISSUE THREAD

**Issue by AriaMoradi** [Suwayomi/Suwayomi-Server#17]
- Komga -> needs support for extension SharedPreferences 
- TsukiMangás(PT) -> needs support for extension SharedPreferences 
- LANraragi -> needs support for extension SharedPreferences 
- Cubari -> needs expansion of AndroidCompat for `android.os.Looper.getMainLooper` ref: `eu.kanade.tachiyomi.extension.all.cubari.RemoteStorageUtils.handler`
- Manga Plus -> needs investigation

**Comment by arbuilder** [comment]
Is is possible it is related to #19 as we can use komanga inside lan not just local host ex 192.168.1.2

**Comment by AriaMoradi** [comment]
> Is is possible it is related to #19 as we can use komanga inside lan not just localhost ex 192.168.1.2

Nope, it's an internal java issue...

**Comment by arbuilder** [comment]
> Nope, it's an internal java issue...

same issue with LANraragi, can't install it

**Comment by jobobby04** [comment]
* E-Hentai -> Manga and chapter loading is broken

**Comment by AriaMoradi** [comment]
> * E-Hentai -> Manga and chapter loading is broken

I found a fork that fixes some dex2jar bugs, and E-Hentai works with `master` now, you can build a new jar from that.

**Comment by arbuilder** [comment]
hmm, there might be some language issues also in tachidesk

![Screenshot](https://user-images.githubusercontent.com/78140816/122120207-c18a5380-ce47-11eb-9c5d-67bc17db9c52.png)

**Comment by prorounak2005** [comment]
nhentai is npt working for me too
![image](https://user-images.githubusercontent.com/69617708/124654280-03913d00-debc-11eb-8215-99d8fd3bd7c2.png)

**Comment by prorounak2005** [comment]
it keeps buffering

**Comment by AriaMoradi** [comment]
closed in favor of #161
