### ISSUE TITLE
[Feature Request] Simple user authentication

### ISSUE THREAD

**Issue by pseudokawaii** [Suwayomi/Suwayomi-Server#193]
A simple user authentication using username & password or only password before entering the app. Since Tachidesk is actually a server application and can be used like a web app, don't you think a user authentication feature will be very useful? A node without any auth check is open to the public, not very privacy-friendly.

**Comment by AriaMoradi** [comment]
I added BasicAuth support in bd638251e4aaf5f2039f518467d1f6551f2716cb (r915).

I won't work on more sophisticated solutions for the time being as Tachidesk is intended to be executed and used locally.
