### ISSUE TITLE
[Feature Request] Implement Unread Count on Manga level

### ISSUE THREAD

**Issue by mrsOwlex** [Suwayomi/Suwayomi-Server#224]
## What feature should be added to Tachidesk?
The Api should return how many Chapters of a Manga in the library are unread.

##  Why/Project's Benefit/Existing Problem
This would enable the UIs to implement a Unread Badge. Furthermore a proper implementation would make it possible to implement the Tachiyomi Style Filter Unread/Read on the Category Level.

**Comment by AriaMoradi** [comment]
related issue: https://github.com/Suwayomi/Tachidesk-WebUI/issues/37

**Comment by AriaMoradi** [comment]
Just a pointer: Tachiyomi provides two kind of badges: unread and downloaded badges
