### ISSUE TITLE
[Feature Request] Save chapter as CBZ

### ISSUE THREAD

**Issue by Nonobis** [Suwayomi/Suwayomi-Server#33]
## What feature should be added to Tachidesk?
Explain What the feature is and how it should work in detail

Could you add an option save chapter as cbz ?

##  Why/Project's Benefit/Existing Problem
Explain why this should be added

Saving as CBZ will save place when downloading chaters

**Comment by BradKML** [comment]
Question: What benefits does CBZ have over EPUB/MOBI/DJVU? Or is it merely a container and compression specification?
Another question: Would the image files contained in the CBZ be JPG/PNG or could it be something more advanced like JPEG-XL?

- https://cloudinary.com/blog/how_jpeg_xl_compares_to_other_image_codecs
- https://chipsandcheese.com/2021/02/28/modern-data-compression-in-2021-part-2-the-battle-to-dethrone-jpeg-with-jpeg-xl-avif-and-webp/

**Comment by Nonobis** [comment]
for me merely a container, png is good. I don't known jpeg-xl bug why not.

**Comment by BradKML** [comment]
Considering the idea:
- https://docs.google.com/spreadsheets/d/1ju4q1WkaXT7WoxZINmQpf4ElgMD2VMlqeDN2DuZ6yJ8/edit
- https://www.youtube.com/c/JonSneyers/videos
- https://cloudinary.com/blog/how_jpeg_xl_compares_to_other_image_codecs
- https://eclipseo.github.io/image-comparison-web

**Comment by AriaMoradi** [comment]
I don't have any plans to implement this feature, and it doesn't fit the intended design and usage, if you really want it, you have to come up with a PR first.

**Comment by BradKML** [comment]
@AriaMoradi what if it is purely saving/caching manga tho? that is a default feature for Tachiyomi.

**Comment by AriaMoradi** [comment]
> @AriaMoradi what if it is purely saving/caching manga tho? that is a default feature for Tachiyomi.

Tachidesk already does that. It's in a directory called manga in the data directory.

**Comment by BradKML** [comment]
@AriaMoradi right now the sources page is kind of goofy, and there is nothing I can do to "search" since it is stuck on "loading" (when the plugins are already downloaded), but that is another issue altogether.
https://github.com/Suwayomi/Tachidesk/issues/27 https://github.com/Suwayomi/Tachidesk/issues/26

**Comment by Robonau** [comment]
its sad nothing came of this
cbz is a standard for pretty much every comic reader out there, the lack of support for usable formats makes the download button basically useless (what good is downloading if what you get isn't directly usable (adding EPUB/MOBI/PDF is probably also a good idea))

realistically this should be a vary simple add since a cbz is just a renamed zip
each chapter being its own cbz

**Comment by AriaMoradi** [comment]
Tachidesk (and Tachiyomi) save chapter images in a plain image format, in the format the source provides them, it's essentially a local/saved/snapshot/cache of the source, saving it in cbz doesn't make sense. the images are usually highly compressed, why compress them again?

If it's for easier viewing, you should use the client's provided image viewer, it's what the app does after all.
If you need the saving az cbz for archiving proposes, then use one of the many manga downloaders out there like FMD2

**Comment by AriaMoradi** [comment]
Tachiyomi might get the feature, look at https://github.com/tachiyomiorg/tachiyomi/pull/6360
If it does, I'll consider porting their solution.

**Comment by Robonau** [comment]
> Tachidesk (and Tachiyomi) save chapter images in a plain image format, in the format the source provides them, it's essentially a local/saved/snapshot/cache of the source, saving it in cbz doesn't make sense. the images are usually highly compressed, why compress them again?
> 
> If it's for easier viewing, you should use the client's provided image viewer, it's what the app does after all. If you need the saving az cbz for archiving proposes, then use one of the many manga downloaders out there like FMD2

a zip/cbz is lossless so nothing is lost in the compression

for me at least the client is missing features that are available with other readers (mainly tracking, komga + malsync (i have suggested malsync add support for tachidesk))

keeping a list manually updated in multiple places is rather inconvenient (not to mention lack of linux support for fmd2)
note:i already have a script to automatically download new chapters in my library (slimier to tachiyomis option to download new chapters (i like having backups)) (running in nodejs along side the tachidesk instance)

note2: the PR seems to have been merged

**Comment by AlyafeiAli** [comment]
> Tachiyomi might get the feature, look at [tachiyomiorg/tachiyomi#6360](https://github.com/tachiyomiorg/tachiyomi/pull/6360) If it does, I'll consider porting their solution.

Any updates?

**Comment by gregorybeal** [comment]
This feature has been available in tachiyomi for a while now. It would be fantastic if this could be added to tachidesk.

**Comment by lennie420** [comment]
For me this would not be a matter of compression but gives me the ability to transfer and read the .cbz file on my Kobo ereader. For now I'll stick with Hakuneko.

**Comment by Theangelofspace15** [comment]
> Tachiyomi might get the feature, look at [tachiyomiorg/tachiyomi#6360](https://github.com/tachiyomiorg/tachiyomi/pull/6360) If it does, I'll consider porting their solution.

Now that tachiyomi has the option, can we get the option to save as cbz? I also like saving and reading from cbz.let me organize everything by MANGA/CHAPTERS.cbz and the format is pretty much use by all the clients I used.

**Comment by fatotak** [comment]
I'd love to see this implemented.

In addition to this, I'd like to suggest either of the following (when this option is enabled):
1. Download images to RAM, and then only save to disk the CBZ.  (single write works better than write, write, write, compress delete on multiple file systems including slow disks, SSDs (for wear durability), ZFS, and so on)/
2. Alternatively, allow users to configure a scratch location to download to (i.e., in my case, I'd configure scratch as a mdadm raid 0 tmp vol, and perm download as a zfs pool), and then move the file to the permanent location when compressing.

Right now, I have to set my tachidesk DL location to the scratch disk, and then run a custom script to zip them up and move them to my zfs pool every so often.

**Comment by HongYue1** [comment]
I also support this feature, I have no problem with PNG myself, but when my manga library reached 250K+ images, it made the thought of moving it to another place a nightmare.

**Comment by AngelaDMerkel** [comment]
I sync my tachidesk library to drive using rclone and having CBZ would improve performance significantly. Uploading and indexing (literally) 100s of thousands of files is rather slow when compared to the speed that can be accomplished with fewer, but larger, files. If tachidesk were to implement this it would also allow using the docker rclone volume plugin and therefore reading and writing directly to a mount. This would be very useful. 

Re @fatotak suggestion:
> Download images to RAM, and then only save to disk the CBZ. (single write works better than write, write, write, compress delete on multiple file systems including slow disks, SSDs (for wear durability), ZFS, and so on)/

Having a scratch location would be more ideal for systems pressed for memory. I run tachidesk on an rPi to minimise power consumption, alongside a few always on services. Parallel downloads like Tachiyomi has in addition to writing to ram could be a concern on lower memory systems.
