### ISSUE TITLE
[Feature Request] <Back to Browse Button on Manga Overview Page>

### ISSUE THREAD

**Issue by PlatnaX** [Suwayomi/Suwayomi-Server#35]
I think incorporaring a back button on the top left of the manga overview page (similarly to the exit button in the reader) that goes back to browsing the selected source would be such a big quality of life improvement especially if it remembers the browsing location. Right now if I select a manga I have to select the source and browse all over again. BTW I'm using Tachidesk in fullscreen mode so the back arrow isnt shown, and even if I press it, it either doesnt remember the previous location or goes back to the reader if I exited the reader using the top left escape button.

**Comment by AriaMoradi** [comment]
You could open Manga in a new tab..
