### ISSUE TITLE
[Feature Request] Bundle download of Plugins

### ISSUE THREAD

**Issue by BradKML** [Suwayomi/Suwayomi-Server#47]
**PLEASE READ THIS**

## What feature should be added to Tachidesk?
Since https://github.com/tachiyomiorg/tachiyomi-extensions/issues/5672 is in progress, it would be useful if one can download multiple extensions based on a keyword (e.g. English, anything that does not have "Manhua", webcomics)...

##  Why/Project's Benefit/Existing Problem
As a composite problem to https://github.com/Suwayomi/Tachidesk/issues/27, it would be useful to search niche manga through this method. If Tachiyomi is removing this feature due to bad implementations, Tachidesk can make this concept viable again.

**Comment by AriaMoradi** [comment]
Tachidesk will never have this feature, implement it in a fork if you need it.
