### ISSUE TITLE
[Feature] Will it be available on docker after it comes out of development

### ISSUE THREAD

**Issue by Zw012d** [Suwayomi/Suwayomi-Server#5]
It is quite complicate to run and install for users with less coding experience and troubleshooting bugs in the initial install itself. Would it possible for you to create a docker image when it comes out of development so could run it as docker container thanks.

**Comment by AriaMoradi** [comment]
How is running 4 commands more complicated that installing and setting up docker?!

**Comment by Zw012d** [comment]
Hi first of all thanks for working on this project, i thought no one was working on something like this after tachiweb which was abandoned. Just checked it on discord about its development as i was looking for app like this which can be used across platforms. 

> How is running 4 commands more complicated that installing and setting up docker?!

Running these commands if they throws some errors would not be sure if they can be skipped and ignored. But main issue is when we will update we would be sure we will have to update repo and run all/some commands every time and chances of messing up increases. 

Running it in container will perform exactly as initially tested and it would be isolated and easily upgradable without touching our configuration and manga files.

I am only considering docker when it will leave the development cycle and we can finally use it across devices on out local lan without worrying about different app across diff platforms (ios win android etc.)

On a side note i am getting stuck at 94% on ./gradlew :server:run command i am pretty sure i have done something wrong either a pkg missing or maybe issues related to WSL 2  as i was testing if i could run it on WSL 2. 

![Screenshot 2021-01-03 060928](https://user-images.githubusercontent.com/76645315/103469599-db017c80-4d8c-11eb-8299-fd4418db65f3.png)

**Comment by AriaMoradi** [comment]
Probably the app will be distributed as a fat jar or an electron app, running it will be simple then. I don't mess with docker, if anyone is interested in "dockerizing" they should PR the `dockerfile`(or whatever is needed to run docker...).

> On a side note i am getting stuck at 94% on ./gradlew :server:run command i am pretty sure i have done something wrong either a pkg missing or maybe issues related to WSL 2 as i was testing if i could run it on WSL 2.

It's actually fine! The server is running as a part of a gradle task, so it will be stuck in the `EXECUTING` state. 

If more users are interested in development on windows, I'll do something about `getAndroid.sh` to make it possible to run cross-platform even for development.

**Comment by Zw012d** [comment]
> Probably the app will be distributed as a fat jar or an electron app, running it will be simple then. I don't mess with docker, if anyone is interested in "dockerizing" they should PR the dockerfile(or whatever is needed to run docker...).

Yes it would be much simpler, will be waiting patiently for a release as i was looking for a cross-platform application for a long time which can run on a local browser and can be used across platforms like ios android windows.

> It's actually fine! The server is running as a part of a gradle task, so it will be stuck in the EXECUTING state.

I see i thought it might be missing some pkg files :)

> If more users are interested in development on windows, I'll do something about getAndroid.sh to make it possible to run cross-platform even for development.

if it doesn't take too much development time it is a very good idea
