### ISSUE TITLE
[Feature Request] Pre-downloading chapters

### ISSUE THREAD

**Issue by BradKML** [Suwayomi/Suwayomi-Server#51]
## What feature should be added to Tachidesk?
Tachiyomi allows for scanning source comic updates and downloading manga series in one click. Bonus points if the "animal version/mirror duplicates" issues are solved.

##  Why/Project's Benefit/Existing Problem
In case someone were to go offline from WiFi, this would have been a god-send.

**Comment by AriaMoradi** [comment]
This is planned with v0.3.0
