### ISSUE TITLE
[Bug] Unable to read manga.

### ISSUE THREAD

**Issue by DrToxz** [Suwayomi/Suwayomi-Server#59]
---

## Device information
- Tachidesk version: (Tachidesk-v0.2.7-r312-win32)
- Server Operating System: (Windows 10)
- Server Desktop Environment: N/A or (None)
- Server JVM version: bundled with win32 or (bundled with win32)
- Client Operating System: <usually the same as above Server Operating System>
- Client Web Browser: ( Google Chrome Version 89.0.4389.114 (Official Build) (64-bit)) 

## Steps to reproduce
1. First Step
Click any manga from any source
2. Second Step
Try reading
### Expected behavior
It should load and let me read...I presume.
### Actual behavior
It either goes to a completely white screen or infinitely loads the manga.

## Other details

I've tried everything listed IIRC and it has happened with the previous version as well, I have never had it work so last time I thought it would be fixed in a  newer version.

**Comment by K0-RR** [comment]
Why is it so hard for some people to read?

**Comment by DrToxz** [comment]
> Why is it so hard for some people to read?

What didn't I read.

**Comment by SaltyBarnacles** [comment]
You have to install the sources first
