### ISSUE TITLE
[Feature Request] Aid for other applications

### ISSUE THREAD

**Issue by BradKML** [Suwayomi/Suwayomi-Server#61]
## What feature should be added to Tachidesk?
Allow the downloaders to be accessed from other applications e.g.
- https://github.com/Difegue/LANraragi (which has a plugin for download, but not upload)
- https://hydrusnetwork.github.io/hydrus

##  Why/Project's Benefit/Existing Problem
Other applications are better at cataloging large amounts of Manga than Tachiyomi themselves, with tagging and metadata capabilities https://github.com/Suwayomi/Tachidesk/issues/51

**Comment by AriaMoradi** [comment]
This is not in Tachidesk's territory, those apps can use Tachidesk's api when the feature is implemented
