### ISSUE TITLE
[Feature Request] Tachidesk Advanced Backup Support 

### ISSUE THREAD

**Issue by arbuilder** [Suwayomi/Suwayomi-Server#62]
## What feature should be added to Tachidesk?
currently when we click backup it goes to download directory only (from browser). It would be nice to have auto backup with configuration settings like backup location and frequency in the ui.

 Features -

  - make an end point that takes the parameters for automatic backup like backup interval, backup save location, maximum backups ( ex only have 1, 2 or 3 backups and delete older backup when new backup is created)  and also make the front end code that sets those parameters  and also call it from the front end
  
  - warn the user that if the app is not running, it won't backups anything
  
  - develop a feature so the app can run as a service or on startup so the user just has to click on the tray icon to open the app at any time

##  Why/Project's Benefit/Existing Problem

In case we forgot to create manual backup frequently, we have auto backup that can be restored later if something goes wrong

**Comment by joseph619** [comment]
create separate ticket for each request

**Comment by arbuilder** [comment]
> create separate ticket for each request

@joseph619 Not sure what u mean see discord link for relevant chat https://discord.com/channels/801021177333940224/823955309138673695/834074788732993546

**Comment by arbuilder** [comment]
Closing this as features would already be included in #80

**Comment by Syer10** [comment]
Addressed by #595 and #597
