### ISSUE TITLE
[Feature Request] Able to read local files and change save locations

### ISSUE THREAD

**Issue by BaccanoMob** [Suwayomi/Suwayomi-Server#64]
1. Is it possible to implement function to read local files from PC? (possible formats jpg, png, zip, cbz similar to tachiyomi from a local source option)

Because I use tachiyomi a lot, I could just copy the downloads I make in my phone to PC or vice versa rather than downloading multiple times.

2. Currently, if I run tachidesk, the images of each and every single manga I browse or read from whatever I search gets stored at my C drive. Its a huge problem for me because there is hardly any space in it. Possible solutions of what I think would be best:
    a. Option to change the directory.
    b. Option to periodically clean sweep the thumbnails and other folders.

3. (This one is out of curiosity) Could you not open Tachidesk as a separate application window? 

I get that you are trying with link to a browser. Like maybe open up Tachidesk as a different profile (I use multiple chrome profiles so they open up separate but not sure of other browsers) but thanks for the hard work so far you all put into!!

**Comment by joseph619** [comment]
If you want a standalone app of Tachidesk, you can use Tachidesk JUI (which doesn't run on a browser)

https://github.com/Suwayomi/TachideskJUI

I agree with the other points

**Comment by BaccanoMob** [comment]
I actually wanted to have a look at TachideskJUI before but had no idea how to install and try it out (exe files are a lot easier). Ill drop by the discord server later when I find time on how to install it.

Apart from that if you could implement the other two points it be really helpful.

**Comment by AriaMoradi** [comment]
Your first point will be handled when Local source is added, and the other two can be done with some configuration, which don't have documentation right now...
