### ISSUE TITLE
[Feature Request] <Load all images at once>

### ISSUE THREAD

**Issue by huynlx** [Suwayomi/Suwayomi-Server#67]
I mean turn off lazy load in reader and load all images at once. Because some sources  are very slow and when scroll down to images position to load, it took a long time to wait , it would be great if images were preloaded while reading instead of scrolling down to it to load, like other manga reading websites, all images are loaded in 1 page load !!

**Comment by AriaMoradi** [comment]
no lazy loader in recent versions of the app
