### ISSUE TITLE
Ignores Apache license

### ISSUE THREAD

**Issue by nonproto** [Suwayomi/Suwayomi-Server#7]
If you are gonna straight copy Tachiyomi source code and re license it you should make sure you follow the musts.

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by AriaMoradi** [comment]
- No NOTICES
- Changes are visible in the source code? Source files don't include the copyright notice?
- link to APL included in README

what else should I do to comply properly?

**Comment by nonproto** [comment]
looks good to me
