### ISSUE TITLE
[Feature Request] Api should have manga genre as a json array

### ISSUE THREAD

**Issue by Syer10** [Suwayomi/Suwayomi-Server#74]
## What feature should be added to Tachidesk?
Change the genre from a string to a list of strings.

##  Why/Project's Benefit/Existing Problem
In the API currently the genre is shared as a string, with each genre separated by a ", ", this can be handled by the API to allow easier usage in the clients.

**Comment by AriaMoradi** [comment]
fixed in v0.5.0
