### ISSUE TITLE
[Bug][webUI] Manga grid is unusable when covers are missing

### ISSUE THREAD

**Issue by Zw012d** [Suwayomi/Suwayomi-Server#77]
---
## Device information
- Tachidesk version: latest preview 
- Server Operating System: Ubuntu 20.04 wsl
- Server Desktop Environment: Docker
- Server JVM version: openjdk 16
- Client Operating System: win 10 
- Client Web Browser: Google Chrome latest

### Expected behavior
In case covers are missing manga grid shouldn’t become unusable. Maybe some placeholder until cover image are available.
![685FF513-1EBA-47E2-82F7-40134C8AC247](https://user-images.githubusercontent.com/76645315/117250591-13ab8280-ae61-11eb-8db4-089197e37fff.png)

**Comment by Zw012d** [comment]
you have to delete your old tachidesk data to fix the manga grid issue and start fresh

**Comment by AriaMoradi** [comment]
> you have to delete your old tachidesk data to fix the manga grid issue and start fresh

MangaDex 1.2.107 fixes the covers issue, but this issue stands, if ever a source fails to load covers, the grid will be the same.

Maybe add a loading spinner while the image is loading or failed to load.
