### ISSUE TITLE
[Feature Request] Mangadex login

### ISSUE THREAD

**Issue by AriaMoradi** [Suwayomi/Suwayomi-Server#8]
Special modal to get mangadex credentials like neko

**Comment by chaorace** [comment]
I think something like this will also be necessary for other paid services, like the VIZ Shonen Jump extension. In Tachiyomi, these are handled via a webview for presenting the login page and getting the login cookie. Not totally sure how that would map over in a browser, considering CORS.

**Comment by jobobby04** [comment]
In the tachiyomi discord we discussed how to handle logins recently. The Tachiyomi api may get a login interface soon, all Tachidesk would need to do is add a login menu for the sources that implement the interface

**Comment by AriaMoradi** [comment]
mangadex is morphing to v5, this issue is not relevant anymore.
