### ISSUE TITLE
[Bug] Can not load images of chapter

### ISSUE THREAD

**Issue by huynlx** [Suwayomi/Suwayomi-Server#81]
All chapters with colons are broken !!
Image can't load !!
Stuck at loading screen 
![InkedAnnotation 2021-05-13 201016_LI](https://user-images.githubusercontent.com/38340757/118131253-7fc15400-b428-11eb-88b1-2d97ea2de23f.jpg)

**Comment by AriaMoradi** [comment]
which source and which manga?

**Comment by huynlx** [comment]
> which source and which manga?

all source, All chapters with colons at name are broken !

**Comment by AriaMoradi** [comment]
Give a few examples

**Comment by Huynh12345678** [comment]
> Give a few examples

![Uploading Annotation 2021-05-13 202526.png…]()

**Comment by huynlx** [comment]
> Give a few examples

![Annotation 2021-05-13 202526](https://user-images.githubusercontent.com/38340757/118132100-843a3c80-b429-11eb-88fd-d730f7872b2c.png)

**Comment by AriaMoradi** [comment]
I can't reproduce the mentioned issue with your example, `Tsugumomo from Mangakakalot (EN)`

please make sure that you are using the latest version of the app and fill this form:

- Tachidesk version: (Example: v0.2.3-r255-win32)
- Server Operating System: (Example: Ubuntu 20.04)
- Server Desktop Environment: N/A or (Example: Gnome 40)
- Server JVM version: bundled with win32 or (Example: Java 8 Update 281 or OpenJDK 8u281)
- Client Operating System: <usually the same as above Server Operating System>
- Client Web Browser: (Example: Google Chrome 89.0.4389.82)

**Comment by huynlx** [comment]
> I can't reproduce the mentioned issue with your example, `Tsugumomo from Mangakakalot (EN)`
> 
> please make sure that you are using the latest version of the app and fill this form:
> 
> * Tachidesk version: (Example: v0.2.3-r255-win32)
> * Server Operating System: (Example: Ubuntu 20.04)
> * Server Desktop Environment: N/A or (Example: Gnome 40)
> * Server JVM version: bundled with win32 or (Example: Java 8 Update 281 or OpenJDK 8u281)
> * Client Operating System:
> * Client Web Browser: (Example: Google Chrome 89.0.4389.82)

Tachidesk version: Tachidesk-v0.3.0-r430 (Latest)
Server Operating System: Windows 10 Pro for Workstations version 21H1 (64-bit)
Server Desktop Environment: N/A
Server JVM version: Java 8 Update 281 
Client Operating System: Windows 10 Pro for Workstations version 21H1 (64-bit)
Client Web Browser: Microsoft Edge Version 90.0.818.56 (Official build) (64-bit)

**Comment by AriaMoradi** [comment]
possible reason: "colon in directory name doesn't work on some file systems"
