### ISSUE TITLE
[Bug] Can't install extensions - 0.3.3 -Win64 only

### ISSUE THREAD

**Issue by Asinin3** [Suwayomi/Suwayomi-Server#86]
## Device information
- Tachidesk version: v0.3.3-r505-win64
- Server Operating System: N/A, Using localhost
- Server Desktop Environment: N/A
- Server JVM version: bundled with win64
- Client Operating System: Windows 10 20H1
- Client Web Browser: Firefox 88

## Steps to reproduce
1. Install new 0.3.3 win64 version
2. Try to install an extension, it will get stuck on installing.

Tried clearing appdata, same issue. Confirmed another can reproduce, but doesn't  happen if you run .jar file.

**Comment by arbuilder** [comment]
@AriaMoradi The issue is with Tachidesk.exe . If u run using Tachidesk-debug.bat it would work but it will stuck in installing extensions if u run Tachidesk.exe in cmd.

**Comment by AriaMoradi** [comment]
fixed in v0.3.4

**Comment by RisingTM** [comment]
now i have that problem at v7.0

**Comment by Syer10** [comment]
If you have an oracle jre. Try switching to [Temurin](https://adoptium.net/).

Some oracle javas have a bug with one of the file functions that the extension installer uses.

**Comment by RisingTM** [comment]
i tried to install mangalife and comick 
and it kept saying installing and when i went to the extension folder it showed that they are downloaded but, in the app, it read nothing. the local source does work so the app does work but the download extinction does not for some reason.

**Comment by RisingTM** [comment]
> If you have an oracle jre. Try switching to [Temurin](https://adoptium.net/).
> 
> Some oracle javas have a bug with one of the file functions that the extension installer uses.

i dont know that that is sorry ?

**Comment by AbhijeetRoy2107** [comment]
I got the solution

1. Go to `https://tachiyomi.org/extensions/` or just search for `tachiyomi extensions` on your browser.
2. The webpage should show the extensions available to download. If the extensions are not shown, connect to a VPN and refresh the page.
3. Download the extensions you want from the page and then install the extension files from the extensions tab in your tachidesk.

It should work... If it doesn't work or you need any assistance ,just comment here. (:

**Comment by Goatfricker69** [comment]
> I got the solution
> 
> 1. Go to `https://tachiyomi.org/extensions/` or just search for `tachiyomi extensions` on your browser.
> 2. The webpage should show the extensions available to download. If the extensions are not shown, connect to a VPN and refresh the page.
> 3. Download the extensions you want from the page and then install the extension files from the extensions tab in your tachidesk.
> 
> It should work... If it doesn't work or you need any assistance ,just comment here. (:

I tried but it downloads as .apk and it doesn't work

**Comment by AbhijeetRoy2107** [comment]
> > I got the solution
> > 
> > 1. Go to `https://tachiyomi.org/extensions/` or just search for `tachiyomi extensions` on your browser.
> > 2. The webpage should show the extensions available to download. If the extensions are not shown, connect to a VPN and refresh the page.
> > 3. Download the extensions you want from the page and then install the extension files from the extensions tab in your tachidesk.
> > 
> > It should work... If it doesn't work or you need any assistance ,just comment here. (:
> 
> I tried but it downloads as .apk and it doesn't work


Try opening the .apk file in the tachidesk extension tab.
I will try and post a detailed solution in some hours.

**Comment by ragnerath** [comment]
Hello, I recently downloaded Tachidesk 0.7.7 and restored from my phone but when I click on extensions it doesnt show anything, it's just blank. 
Are there any solutions for this? Here's a photo to understand better.
[Pic](https://gyazo.com/b46525999e7c481230daa5a267139c31)

**Comment by Dang0o0** [comment]
Same issue her

> Hello, I recently downloaded Tachidesk 0.7.7 and restored from my phone but when I click on extensions it doesnt show anything, it's just blank. Are there any solutions for this? Here's a photo to understand better. [Pic](https://gyazo.com/b46525999e7c481230daa5a267139c31)

Same issue here
Did you find any sol?

**Comment by Robonau** [comment]
> Hello, I recently downloaded Tachidesk 0.7.7 and restored from my phone but when I click on extensions it doesnt show anything, it's just blank. Are there any solutions for this? Here's a photo to understand better. Pic


> Same issue her
> Same issue here Did you find any sol?

the issue you two hare having isn't an issue you just haven't added a repo to get extensions from
please do that before digging up ancient and closed issues

**Comment by Dang0o0** [comment]
> > Hello, I recently downloaded Tachidesk 0.7.7 and restored from my phone but when I click on extensions it doesnt show anything, it's just blank. Are there any solutions for this? Here's a photo to understand better. Pic
> 
> > Same issue her
> > Same issue here Did you find any sol?
> 
> the issue you two hare having isn't an issue you just haven't added a repo to get extensions from please do that before digging up ancient and closed issues

How do you add a repo?


Also its not really a problem of the past if you cant find the sol by one google search(trust me i tried)

**Comment by Robonau** [comment]
> Also its not really a problem of the past if you cant find the sol by one google search(trust me i tried)

This issue is a problem of the past, it was fixed almost 3 years ago

what you are talking about isn't an issue its you not adding a repo for the server to get extensions from

**Comment by Dang0o0** [comment]
> > Also its not really a problem of the past if you cant find the sol by one google search(trust me i tried)
> 
> This issue is a problem of the past, it was fixed almost 3 years ago
> 
> what you are talking about isn't an issue its you not adding a repo for the server to get extensions from

Ok i figured it out, thanks for being of such great help(sarcasm)

I wanted a small help. I want to download the entirety of a manga but there is  no option for doing is there any extension that does exactly that or maybe there is a option like that I dont know of???

**Comment by Robonau** [comment]
> I wanted a small help. I want to download the entirety of a manga but there is no option for doing is there any extension that does exactly that or maybe there is a option like that I dont know of???

don't continue in an issue after you have already been told to stop

for simple help like that ask in the discord

(on a manga page, select all chapters (is a button in top right ish) > bottom right button chapter options > download selected)
