### ISSUE TITLE
[Feature Request] Urls path according to any site supported by MAL-sync for the use of custom domains.

### ISSUE THREAD

**Issue by Kawerik** [Suwayomi/Suwayomi-Server#91]
Path url according to any of the sites supported by MAL-sync:
https://github.com/MALSync/MALSync/blob/master/pages.md

To use MAL-sync with custom domains:
https://github.com/MALSync/MALSync/wiki/Custom-Domains

**Comment by AriaMoradi** [comment]
this kind of feature is out of Tachidesk's intended use, anyone interested can fork the project and add it.
