### ISSUE TITLE
[Feature Request] Add lastReadAt to chapter

### ISSUE THREAD

**Issue by JipFr** [Suwayomi/Suwayomi-Server#93]
## What feature should be added to Tachidesk?
I would like for a `lastReadAt` field to be added to each chapter in the chapter endpoint for a series.

##  Why/Project's Benefit/Existing Problem
This would allow for "sorting by last read" and would allow apps to highlight the chapter that was most recently read

**Comment by AriaMoradi** [comment]
fixed in latest commit
